Liga Klavina Praktiskais darbs
rudolfs-dudarevs/frontend-javaguru pull request #21
Opened 2022-12-15 21:01 UTC by LigaKlav

2022-12-20 17:48 UTC, rudolfs-dudarevs commented
Šeit ir tikai nodarbības praktiskais darbs. Nepieciešams arī mājasdarbs.

2022-12-22 21:50 UTC, LigaKlav commented
Pievienoju arī mājas darbu. Tur gan ir vairāki jautājumi, kur nepieciešama palīdzība. Paldies!

2023-01-02 05:54 UTC, rudolfs-dudarevs requested changes

2023-01-02 05:54 UTC, rudolfs-dudarevs commented on 2-nodarbiba/uzdevumi/LigaKlavina/homework/css/style.css
> +@keyframes blink{
Šādi definējam animācijas piemēru.

2023-01-02 05:54 UTC, rudolfs-dudarevs commented on 2-nodarbiba/uzdevumi/LigaKlavina/homework/js/apps.js
> +    actionEls.style.animationName = "blink";
Lai panāktu "blink" animāciju, mums vispirms iekš CSS ir jādefinē šī animācija. To vēl neesam apguvuši, bet CSS iekomitoju tavā branch style.css failā piemēru kā definēt animāciju.
Animācija nestrādāja, jo tāda vēl nebija izveidota.

2023-01-02 05:54 UTC, rudolfs-dudarevs commented on 2-nodarbiba/uzdevumi/LigaKlavina/homework/js/apps.js
> + //vai ir iespēja, sadalīt, ka krāsa nomainās uzreiz, bet pēc 3s teksts pazūd? Šeit mēģinājums, bet ne visai veiksmīgs
Šī ir nepareiza setTimeout sintakse. Nedaudz zemāk esmu uzrakstījis koda piemēru funkcijā changeElchStyle() kā šo uzrakstīt pareizi.
Ar šo funkciju gan vienkārši pazudīs pati poga uz kuras tika uzklikšķināts pēc 3 sekundēm.
Kā arī definējot šo setTimeout ārpus jebkādas funkcijas - tās izpildīsies uzreiz pēc lapas ielādes. Proti, lapa ielādēsies un pēc 3 sekundēm pazudīs poga. Tas gan nenostrādās, jo šādi setTimeout vienkārši ir uzrakstīts nepareizi un nenostrādās vispār.

2023-01-02 05:54 UTC, rudolfs-dudarevs commented on 2-nodarbiba/uzdevumi/LigaKlavina/homework/js/apps.js
> +// KODA PIEMĒRS
Ja vēlies, lai uz katras pogas izpildās atšķirīgs kods - nepieciešams deklarēt funkciju priekš katras pogas.
Šeit ir koda piemērs kā Tavu kodu sadalīt 3 dažādās funkcijās. HTML tās neesmu pielicis pie katras pogas, to tev pašai būs jāizdara.

2023-01-02 05:54 UTC, rudolfs-dudarevs commented on 2-nodarbiba/uzdevumi/LigaKlavina/homework/js/apps.js
> +    setTimeout(() => {
Šādi izskatās pareizi uzrakstīts setTimout() un tas iziupildīsies tikai peč klikšķa uz 3. pogas jeb kad tik izsaukta funkcija changeElchStyle.

2023-01-02 05:54 UTC, rudolfs-dudarevs commented on 2-nodarbiba/uzdevumi/LigaKlavina/homework/js/apps.js
> +const actionEls = document.getElementById("blink");
Labāk izvēlēties pilnākus nosaukumus - piem., actionBlinkEl

2023-01-02 05:54 UTC, rudolfs-dudarevs commented on 2-nodarbiba/uzdevumi/LigaKlavina/homework/js/apps.js
> +const actionElch = document.getElementById("color-ch");
LAbāk izvēlēties pilnākus nosaukumus - piem., actionChangeColor

2023-01-12 17:00 UTC, rudolfs-dudarevs approved these changes

2023-01-12 17:02 UTC, merged